- repo: airblade/vim-gitgutter
- repo: bronson/vim-trailing-whitespace
- repo: easymotion/vim-easymotion
- repo: vim-airline/vim-airline
- repo: vim-airline/vim-airline-themes
- repo: joshdick/onedark.vim
- repo: tpope/vim-fugitive
- repo: itchyny/vim-gitbranch
- repo: mhinz/vim-signify
- repo: sheerun/vim-polyglot
- repo: luochen1990/rainbow
- repo: junegunn/fzf
  build: ./install
  merge: 0
- repo: junegunn/fzf.vim
- repo: scrooloose/syntastic
- repo: chase/vim-ansible-yaml
- repo: mattn/emmet-vim
- repo: leafgarland/typescript-vim
- repo: pangloss/vim-javascript
- repo: chemzqm/vim-run
- repo: majutsushi/tagbar
- repo: scrooloose/nerdcommenter
- repo: scrooloose/nerdtree
- repo: Xuyuanp/nerdtree-git-plugin
- repo: terryma/vim-multiple-cursors
- repo: octol/vim-cpp-enhanced-highlight
- repo: tpope/vim-eunuch
- repo: tpope/vim-surround
- repo: fedorenchik/qt-support.vim
- repo: w0rp/ale
- repo: ryanoasis/vim-devicons
- repo: tiagofumo/vim-nerdtree-syntax-highlight
- repo: neoclide/coc.nvim
  merge: 0
  rev: release
- repo: honza/vim-snippets
  depends : coc.nvim
