# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1573250886);
user_pref("app.update.lastUpdateTime.background-update-timer", 1573314924);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1573251051);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1573386361);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1573492564);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1573386493);
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 1573251291);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1573251171);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.display.background_color", "#131516");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1573250578);
user_pref("browser.laterrun.bookkeeping.sessionCount", 48);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 56);
user_pref("browser.newtabpage.blocked", "{\"b3clC6lVG/xv7JBkr2Krhg==\":1,\"0xXZzK2AaZ/E/JzccF+Hvw==\":1,\"WF0nwcFHCTYEHOJNG6mm6A==\":1,\"/R+z2AumZ8eiDQvZ2y8XsQ==\":1,\"X/u1axqIx7x4NnFRrsqrog==\":1,\"LQsmAzmXs69VNpQP/QywUw==\":1,\"/q23mCgUstGss389mNst5A==\":1,\"ylXlrc21M9/qMUZrXN23WQ==\":1,\"yQgv9Z3akaWKD9mWso/b7A==\":1,\"W03mNyC51xjMDNbMy/SHnA==\":1,\"EZB94nnZWMeTUSf2P92W1g==\":1,\"jqygRExa1cZReMumWve4lA==\":1,\"fKl7x2NmNaQ1+fbKYq2Ezw==\":1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1573492540657");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1573496140657");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.hiddenOneOffs", "Bing,Qwant,Ecosia,Google,StartPage,Wikipedia (en),Yahoo");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "MOZ_BUILDID");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1573492536");
user_pref("browser.startup.homepage", "about:newtab");
user_pref("browser.startup.homepage_override.buildID", "MOZ_BUILDID");
user_pref("browser.startup.homepage_override.mstone", "56.2.14");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"e10s-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"addon_darkreader_org-browser-action\",\"adguardadblocker_adguard_com-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\",\"webide-button\",\"adguardadblocker_adguard_com-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20191108);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.debugger.prefs-schema-version", "1.0.2");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"56.2.14\"}");
user_pref("devtools.toolbox.host", "window");
user_pref("devtools.toolbox.previousHost", "bottom");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 350);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190903144949");
user_pref("extensions.lastAppVersion", "56.2.14");
user_pref("extensions.lastPlatformVersion", "56.2.14");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"addon@darkreader.org\":\"ec86bb6b-9565-4ac8-9edb-58b1c01b4443\",\"{22e3ad25-715c-448e-a509-d6853b3e5d87}\":\"47a4cd59-42f1-45d0-a697-d6486c60fa54\",\"adguardadblocker@adguard.com\":\"48a6f12b-7d7f-47ba-8fd1-f75ce5c2597f\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("general.warnOnAboutConfig", false);
user_pref("idle.lastDailyNotification", 1573316687);
user_pref("lightweightThemes.persisted.footerURL", false);
user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1573250579);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "MOZ_BUILDID");
user_pref("media.gmp-manager.lastCheck", 1573492536);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1573316687);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.restore_default", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1573316687);
user_pref("toolkit.startup.last_success", 1573492532);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
