#! /bin/sh

sxhkd &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
compton --config ~/.config/compton/compton.conf &
xmodmap ~/.Xmodmap &
feh --bg-center ~/.wallpaper/lock.png &
urxvtd -q -o -f &
xrandr --output HDMI2 --mode 1920x1080 --output DP1 --mode 1920x1080 --pos 1920x0 --output eDP1 --mode 1920x1080 --pos 3840x0 &

bspc monitor HDMI2 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          0

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
